apiVersion: v1
kind: Pod
metadata:
  name: mc-maintenance
  namespace: minecraft
spec:
  containers:
    - name: alpine
      image: alpine:latest
      command: ["/bin/sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: storage
          mountPath: /data
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: vanilla-paper-pvc
